/**
 * Tests for the pure HTML document builder used by the `report` tool.
 *
 * The builder is intentionally pure (no async, no I/O), so these tests
 * cover the structural guarantees that are easy to regress:
 *   - DOCTYPE + meta charset + viewport are emitted unconditionally.
 *   - The strict CSP `<meta>` tag is present and locks down remote
 *     fetches without `'unsafe-eval'`.
 *   - Title / description / timestamp are HTML-escaped at the
 *     attribute and text positions.
 *   - The body fragment is inserted verbatim (no sanitisation).
 */

import { describe, expect, it } from 'vitest';
import { buildReportHtml } from '@main/tools/reportTemplate';

describe('buildReportHtml', () => {
  it('emits a complete HTML5 document shell', () => {
    const html = buildReportHtml({
      title: 'My Report',
      body: '<p>hello</p>',
      generatedAt: '2026-05-10T09:00:00Z'
    });
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('<meta name="viewport"');
    expect(html).toContain('<meta name="generator" content="Vyotiq · Agent V">');
    expect(html).toContain('</html>\n');
  });

  it('embeds a strict CSP meta tag without unsafe-eval', () => {
    const html = buildReportHtml({ title: 't', body: '<p/>' });
    expect(html).toMatch(/<meta http-equiv="Content-Security-Policy" content="[^"]+"/);
    expect(html).toContain("default-src 'none'");
    expect(html).toContain("img-src 'self' data:");
    expect(html).not.toContain("'unsafe-eval'");
  });

  it('renders the title in <h1>, <title>, and the doc head', () => {
    const html = buildReportHtml({ title: 'Workspace Survey', body: '<p/>' });
    expect(html).toMatch(/<title>Workspace Survey<\/title>/);
    expect(html).toMatch(/<h1>Workspace Survey<\/h1>/);
  });

  it('renders the optional description as a subtitle', () => {
    const html = buildReportHtml({
      title: 't',
      description: 'Per-extension counts.',
      body: '<p/>'
    });
    expect(html).toContain('Per-extension counts.');
    // The subtitle paragraph element itself is what we care about
    // (the class name also appears in the embedded CSS rule, which
    // is present unconditionally).
    expect(html).toContain('<p class="vyotiq-report__subtitle">');
  });

  it('omits the subtitle paragraph when no description is set', () => {
    const html = buildReportHtml({ title: 't', body: '<p/>' });
    // The CSS rule for `.vyotiq-report__subtitle` is always emitted,
    // but no `<p>` carrying that class should be in the body when
    // there's no description.
    expect(html).not.toContain('<p class="vyotiq-report__subtitle">');
  });

  it('escapes title and description text but inserts body verbatim', () => {
    // Title escaping: `<` becomes `&lt;`, `"` becomes `&quot;`, etc.
    // Body verbatim: the model authored it; the doc is read by the
    // user via `file://` in their own browser; CSP blocks remote
    // reach. Sanitisation here would mostly mangle legitimate
    // inline `<svg>` / `<style>`.
    const html = buildReportHtml({
      title: 'A <b> & "quote"',
      description: '<script>x</script>',
      body: '<svg viewBox="0 0 10 10"><circle cx="5" cy="5" r="4"/></svg>'
    });
    expect(html).toContain('A &lt;b&gt; &amp; &quot;quote&quot;');
    expect(html).toContain('&lt;script&gt;x&lt;/script&gt;');
    expect(html).toContain('<svg viewBox="0 0 10 10">');
    expect(html).toContain('<circle cx="5" cy="5" r="4"/>');
  });

  it('renders a footer with the supplied generation timestamp', () => {
    const html = buildReportHtml({
      title: 't',
      body: '<p/>',
      generatedAt: '2026-05-10T14:25:00.000Z'
    });
    expect(html).toContain('Generated by <strong>Agent V</strong>');
    expect(html).toContain('2026-05-10T14:25:00.000Z');
  });
});
