/**
 * Pure HTML document builder for the `report` tool.
 *
 * Takes a model-authored body fragment and wraps it in a self-contained
 * HTML5 document with:
 *
 *   - A strict CSP `<meta>` tag that blocks every remote fetch but
 *     allows inline styles + scripts (so model-emitted SVG or
 *     interactive DOM works without `'unsafe-eval'`).
 *   - A clean, print-friendly stylesheet (light theme — the file lives
 *     in the user's default browser; the in-app stealth-dark tokens
 *     would look wrong outside the app).
 *
 * The function is intentionally pure and stays trivially testable; the
 * only async work happens upstream in the `report` tool.
 *
 * IMPORTANT: the model's `body` is inserted verbatim. There is no
 * sanitisation step. The threat model for a Vyotiq report is:
 *
 *   1. Author = the user's own LLM run inside the user's workspace.
 *   2. Reader = the user, opening the file in their own browser.
 *
 * Both endpoints are inside the trust boundary the user already
 * granted by running Agent V against this workspace. The CSP meta
 * still blocks remote network reach, so even an actively malicious
 * model can't exfiltrate data from the saved file. Sanitisation
 * (e.g. DOMPurify) would mostly mangle legitimate inline `<svg>` and
 * `<style>` chart output — we treat it as out of scope for v1.
 */

export interface BuildReportInput {
  /** Doc title — also used for the `<h1>` and the OS window/tab title. */
  title: string;
  /** Optional one-line subtitle rendered below the title. */
  description?: string;
  /** Model-authored HTML fragment. Wrapped verbatim inside `<main>`. */
  body: string;
  /** Generation timestamp (ISO). Defaults to `new Date().toISOString()`. */
  generatedAt?: string;
}

/** Build the full HTML5 document. Pure; never throws. */
export function buildReportHtml(input: BuildReportInput): string {
  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const safeTitle = escapeHtml(input.title);
  const safeDescription = input.description ? escapeHtml(input.description) : '';

  // CSP rationale:
  //   default-src 'none'  — no implicit network reach for any directive
  //                         not explicitly listed below.
  //   style-src/script-src 'unsafe-inline' — the saved file IS the
  //                         inlined-styles-and-scripts surface; this is
  //                         the whole point of a self-contained
  //                         deliverable. We do NOT add 'unsafe-eval'.
  //   img-src 'self' data: — allows model-emitted data-URI charts /
  //                         icons. `'self'` covers the file-on-disk
  //                         origin when opened via `file://`.
  //   font-src 'self' data: — same rationale for inline icon fonts.
  //   connect-src/frame-src 'none' (inherited from default-src) —
  //                         locks out fetch, XHR, WebSocket, iframes.
  const csp =
    "default-src 'none'; " +
    "style-src 'unsafe-inline' 'self'; " +
    "script-src 'unsafe-inline' 'self'; " +
    "img-src 'self' data:; " +
    "font-src 'self' data:; " +
    "base-uri 'none'; " +
    "form-action 'none'";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<meta name="generator" content="Vyotiq · Agent V">
<title>${safeTitle}</title>
<style>${BASE_STYLES}</style>
</head>
<body>
<main class="vyotiq-report">
<header class="vyotiq-report__header">
<h1>${safeTitle}</h1>
${safeDescription ? `<p class="vyotiq-report__subtitle">${safeDescription}</p>` : ''}
</header>
<section class="vyotiq-report__body">
${input.body}
</section>
<footer class="vyotiq-report__footer">
Generated by <strong>Agent V</strong> · ${escapeHtml(generatedAt)}
</footer>
</main>
</body>
</html>
`;
}

/**
 * Minimal HTML escape for attribute and text positions. Intentionally
 * narrow: only escapes the four characters that change parser state in
 * an attribute or text node. Used on title/description/timestamp —
 * NOT on the body, which is inserted verbatim by design.
 */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Print-friendly base styles. Light theme deliberately — this file
 * lives in the user's default browser as a standalone document and
 * the in-app stealth-dark tokens would look out of place there.
 *
 * The styles are scoped under `.vyotiq-report` to minimise collisions
 * with anything the model writes inside the body fragment.
 */
const BASE_STYLES = `
:root {
  color-scheme: light;
  --vy-bg: #ffffff;
  --vy-fg: #1a1a1f;
  --vy-fg-muted: #5b5b66;
  --vy-fg-faint: #8a8a93;
  --vy-rule: #e6e6ea;
  --vy-surface: #f7f7f9;
  --vy-surface-strong: #eef0f3;
  --vy-accent: #5a4af0;
  --vy-success: #1f8a4d;
  --vy-danger: #c9302c;
  --vy-radius: 8px;
  --vy-mono: ui-monospace, SFMono-Regular, "JetBrains Mono", Menlo, Consolas, monospace;
  --vy-sans: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--vy-bg);
  color: var(--vy-fg);
  font-family: var(--vy-sans);
  font-size: 15px;
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
.vyotiq-report {
  max-width: 880px;
  margin: 0 auto;
  padding: 56px 32px 96px;
}
.vyotiq-report__header { margin-bottom: 32px; }
.vyotiq-report__header h1 {
  font-size: 28px;
  font-weight: 700;
  line-height: 1.2;
  margin: 0 0 8px;
  letter-spacing: -0.01em;
}
.vyotiq-report__subtitle {
  margin: 0;
  color: var(--vy-fg-muted);
  font-size: 15px;
}
.vyotiq-report__body h1,
.vyotiq-report__body h2,
.vyotiq-report__body h3,
.vyotiq-report__body h4 {
  margin: 28px 0 12px;
  line-height: 1.25;
  letter-spacing: -0.005em;
}
.vyotiq-report__body h2 { font-size: 22px; font-weight: 700; }
.vyotiq-report__body h3 { font-size: 18px; font-weight: 600; }
.vyotiq-report__body h4 { font-size: 16px; font-weight: 600; color: var(--vy-fg-muted); }
.vyotiq-report__body p { margin: 0 0 16px; }
.vyotiq-report__body a { color: var(--vy-accent); text-decoration: none; border-bottom: 1px solid currentColor; }
.vyotiq-report__body a:hover { opacity: 0.8; }
.vyotiq-report__body ul,
.vyotiq-report__body ol { padding-left: 24px; margin: 0 0 16px; }
.vyotiq-report__body li { margin-bottom: 4px; }
.vyotiq-report__body code {
  font-family: var(--vy-mono);
  font-size: 13px;
  background: var(--vy-surface);
  padding: 1px 5px;
  border-radius: 4px;
}
.vyotiq-report__body pre {
  font-family: var(--vy-mono);
  font-size: 13px;
  background: var(--vy-surface);
  border: 1px solid var(--vy-rule);
  border-radius: var(--vy-radius);
  padding: 14px 16px;
  overflow-x: auto;
  line-height: 1.5;
  margin: 0 0 16px;
}
.vyotiq-report__body pre code { background: transparent; padding: 0; }
.vyotiq-report__body table {
  border-collapse: collapse;
  width: 100%;
  margin: 0 0 16px;
  font-size: 14px;
}
.vyotiq-report__body th,
.vyotiq-report__body td {
  text-align: left;
  padding: 8px 12px;
  border-bottom: 1px solid var(--vy-rule);
}
.vyotiq-report__body th {
  font-weight: 600;
  background: var(--vy-surface);
  color: var(--vy-fg-muted);
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}
.vyotiq-report__body blockquote {
  margin: 0 0 16px;
  padding: 8px 16px;
  border-left: 3px solid var(--vy-accent);
  color: var(--vy-fg-muted);
  background: var(--vy-surface);
  border-radius: 0 var(--vy-radius) var(--vy-radius) 0;
}
.vyotiq-report__body figure { margin: 16px 0; text-align: center; }
.vyotiq-report__body figcaption {
  font-size: 13px;
  color: var(--vy-fg-muted);
  margin-top: 6px;
}
.vyotiq-report__body svg { max-width: 100%; height: auto; }
.vyotiq-report__body hr {
  border: none;
  border-top: 1px solid var(--vy-rule);
  margin: 32px 0;
}
.vyotiq-report__footer {
  margin-top: 64px;
  padding-top: 16px;
  border-top: 1px solid var(--vy-rule);
  color: var(--vy-fg-faint);
  font-size: 12px;
}
@media (prefers-color-scheme: dark) {
  :root { color-scheme: dark; }
  /*
    Light theme is intentional even in dark-mode browsers — this is a
    "document the user shares with someone" surface, not a chrome
    surface. We respect the prefers-color-scheme keyword only to avoid
    the OS-level form-control hover state from going inverted.
  */
}
@media print {
  .vyotiq-report { padding: 0; max-width: none; }
  .vyotiq-report__footer { page-break-inside: avoid; }
}
`;
